BAI_app_v2/urls.py
from django.urls import path
from BAI_app_v2 import views
from django.contrib.auth import views as auth_views

app_name = 'BAI_app_v2'

urlpatterns = [
    path('signup/',views.signup,name = 'signup'),
    path('user_login/',views.user_login,name="user_login"),
    path('login/',views.user_login,name="login"),
    path('',views.participant_logout,name="participant_logout"),
    path('form1_1/',views.form1_1,name="form1_1"),
    path('form1_2/',views.form1_2,name="form1_2"),
    path('form1_3/',views.form1_3,name="form1_3"),
    path('form1_4/',views.form1_4,name="form1_4"),
    path('form2_1/',views.form2_1,name="form2_1"),
    path('form2_2/',views.form2_2,name="form2_2"),
    path('form2_3/',views.form2_3,name="form2_3"),
    path('form3/',views.form3,name="form3"),
    path('form0/',views.form0,name="form0"),
    path('user_landing/',views.user_landing,name="user_landing"),
    path('user_profile/',views.user_profile,name="user_profile"),
    path('change_pass/',views.change_pass,name='change_pass'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='BAI_app_v2/PasswordReset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='BAI_app_v2/PasswordResetDone.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='BAI_app_v2/PasswordResetConfirm.html'),name='password_reset_comfirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='BAI_app_v2/PasswordResetComplete.html'),name='password_reset_complete'),
    path('activate/<uidb64>/<token>/',views.activate,name="activate"),
    path('adminBAI/',views.adminBAI,name="adminBAI"),
    path('admin_home/',views.admin_home,name="admin_home"),
    path('add_jury/',views.add_jury,name="add_jury"),
    path('admin_verified/',views.admin_verified,name="admin_verified"),
    path('admin_notverified/',views.admin_notverified,name="admin_notverified"),
    path('view_jury/',views.view_jury,name="view_jury"),

    path('viewForm1_1/<user>/<int:cat_id>',views.viewForm1_1,name="viewForm1_1"),
    path('viewForm1_2/<user>/<int:cat_id>',views.viewForm1_2,name="viewForm1_2"),
    path('viewForm1_3/<user>/<int:cat_id>',views.viewForm1_3,name="viewForm1_3"),
    path('viewForm1_4/<user>/<int:cat_id>',views.viewForm1_4,name="viewForm1_4"),
    path('viewForm2_1/<user>/<int:cat_id>',views.viewForm2_1,name="viewForm2_1"),
    path('viewForm2_2/<user>/<int:cat_id>',views.viewForm2_2,name="viewForm2_2"),
    path('viewForm2_3/<user>/<int:cat_id>',views.viewForm2_3,name="viewForm2_3"),
    path('viewForm3/<user>/<int:cat_id>',views.viewForm3,name="viewForm3"),

    path('AcceptForm/<user>/<int:cat_id>',views.AcceptForm,name="AcceptForm"),
    path('RejectForm/<user>/<int:cat_id>',views.RejectForm,name="RejectForm"),

    path('updateform0/<user>/<int:cat_id>',views.updateform0,name="updateform0"),
    path('updateform1_1/<user>/<int:cat_id>',views.updateform1_1,name="updateform1_1"),
    path('updateform1_2/<user>/<int:cat_id>',views.updateform1_2,name="updateform1_2"),
    path('updateform1_3/<user>/<int:cat_id>',views.updateform1_3,name="updateform1_3"),
    path('updateform1_4/<user>/<int:cat_id>',views.updateform1_4,name="updateform1_4"),
    path('updateform2_1/<user>/<int:cat_id>',views.updateform2_1,name="updateform2_1"),
    path('updateform2_2/<user>/<int:cat_id>',views.updateform2_2,name="updateform2_2"),
    path('updateform2_3/<user>/<int:cat_id>',views.updateform2_3,name="updateform2_3"),
    path('updateform3/<user>/<int:cat_id>',views.updateform3,name="updateform3"),

    path('update_view/',views.update_view,name="update_view"),
    path('show_updateform0/<user>/<int:cat_id>',views.show_updateform0,name="show_updateform0"),


]

BAI_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from BAI_app_v2 import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('BAI_app_v2/',include('BAI_app_v2.urls')),
    path('', include('django.contrib.auth.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BAI_app_v2/views.py
from django.shortcuts import render,redirect
from BAI_app_v2.forms import (ParticipantInfoForm,SignUpForm,SpeedForm,SafetynWellfareForm,
                                OthersForm,EconomyForm,Project_infoForm, Project_info_1Form, 
                                QualityForm,CategoryForm, PaymentDetailsForm, UserCategoryForm, JurySignUpForm, JuryInfoForm)
from BAI_app_v2.models import (UserCategory, Category, PaymentDetails, Quality, Project_info, 
                                Project_info_1, Economy, Others,SafetynWellfare, Speed, JurySignup)
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm

from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_text,DjangoUnicodeDecodeError
from .utils import account_activation_token
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
#from verify_email.email_handler import send_verification_email
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model
UserModel = get_user_model()
# Create your views here.

cat_id = {
    "Residential (bungalow, row houses, standalone buildings)":1,
    "Residential (housing complex)":2,
    "Residential ( affordable housing)":3,
    "Commercial (malls, office, institution, hotel, hospital, cinema)":4,
    "Industrial (any size, any type)":5,
    "Infrastructure (bridges, flyovers, ESR etc.)":6,
    "Well equipped, well mechanized site":7,
    "Government, Semi-Govt., Public Works":8,
    "Work upto Bare Shell (includes RCC, Masonry and Plaster works)":9
}

cat = {
    1:"Residential (bungalow, row houses, standalone buildings)",
    2:"Residential (housing complex)",
    3:"Residential ( affordable housing)",
    4:"Commercial (malls, office, institution, hotel, hospital, cinema)",
    5:"Industrial (any size, any type)",
    6:"Infrastructure (bridges, flyovers, ESR etc.)",
    7:"Well equipped, well mechanized site",
    8:"Government, Semi-Govt., Public Works",
    9:"Work upto Bare Shell (includes RCC, Masonry and Plaster works)"
}

def home(request):
    return render(request,'BAI_app_v2/index.html')

def adminBAI(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        adminUser = authenticate(request,username=username,password=password)

        if adminUser is not None:
            if adminUser.is_active and adminUser.is_superuser:
                login(request,adminUser)
                return render(request,'BAI_app_v2/admin_home.html',{'adminUser':adminUser})

            else:
                return HttpResponse("Not Authorised to access Admin page! OR Account not active!")

        else:
            messages.add_message(request, 40, 'Invalid Login credentials')
            return redirect('BAI_app_v2/admin_login.html')
    else:
        return render(request,'BAI_app_v2/admin_login.html')


@user_passes_test(lambda u: u.is_superuser)
def admin_home(request):
    return render(request,'BAI_app_v2/admin_home.html')

@user_passes_test(lambda u: u.is_superuser)
def add_jury(request):
    if request.method == 'POST':
        jury_signup_form = JurySignUpForm(data=request.POST)
        # user = jury_signup_form.save(commit = False)
        # try:
        #     validate_password(user.password,user)
        # except ValidationError as e:
        #     jury_signup_form.add_error('password',e)

        jury_info_form = JuryInfoForm(data=request.POST)
        if jury_signup_form.is_valid() and jury_info_form.is_valid():
            user = jury_signup_form.save()
            user.email = user.username
            user.set_password(user.password)
            user.is_staff = True
            user.save()
            profile = jury_info_form.save(commit = False)


            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('BAI_app_v2/active_email_jury.html',
                                       {
                                           'user': user,
                                           'domain': current_site.domain,
                                           'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                           'token': default_token_generator.make_token(user),
                                       }
                                       )
            email_subject = 'Builders Association of India Account Verification.'

            to_email = user.email
            email = EmailMessage(
                email_subject,
                message,
                to=[to_email]
            )
            email.send(fail_silently=True)
            profile.user = user
            profile.save()

            return HttpResponse("Correct")

        else:
            print(jury_signup_form.errors, jury_info_form.errors)
            return HttpResponse("Wrong")

    return render(request,'BAI_app_v2/add_jury.html',{'form':JuryInfoForm})


@user_passes_test(lambda u: u.is_superuser)
def admin_verified(request):
    all_entries = list()
    q = Category.objects.filter(status=1)
    for itr in q:
        sub_entry = list()
        sub_entry.append(itr.users_name)
        sub_entry.append(cat_id[itr.app_form_cat])
        sub_entry.append(itr.app_form_cat)
        #sub_entry.append(itr.status)
        all_entries.append(sub_entry)
    return render(request,'BAI_app_v2/admin_verified.html',{"verified":all_entries})

@user_passes_test(lambda u: u.is_superuser)
def admin_notverified(request):

    # if request.method == "POST":
    #     #Q = Category.objects.get(users_name=request.user.username)
    #     user = Category.objects.filter(users_name=request.user.username).filter(app_form_cat=request.POST['app_form_cat'])
    #     print(user)
    #     if request.POST.get('status'):
    #         user.status = request.POST.get('status')
    #         for objs in user:
    #             objs.save()
    #         return HttpResponse('Accepted/Rejected....Check Admin page!!!')
    #     else:
    #         return HttpResponse('chuklay ikde!!!')

    all_entries = list()
    #q1 = Category.objects.filter(users_name).filter(app_form_cat)
    q1 = Category.objects.filter(status=0)
    #print(q1)
    for itr in q1:
        count = 0
        user = itr.users_name
        cat = itr.app_form_cat

        test = [Project_info,Project_info_1,Quality,Economy,Speed,PaymentDetails,Others,SafetynWellfare]
        for i in test:
            q = i.objects.filter(users_name=user).filter(category_latest=cat)
            if len(q)>0:
                count = count+1

        if count==8:
            sub_entry = list()
            sub_entry.append(user)
            sub_entry.append(cat_id[cat])
            sub_entry.append(cat)
            all_entries.append(sub_entry)
    
    return render(request,'BAI_app_v2/admin_notverified.html',{'all_entries':all_entries})  

@user_passes_test(lambda u: u.is_superuser)
def AcceptForm(request,user,cat_id):
    category = cat[cat_id]
    #q = Category.objects.filter(users_name=user).filter(app_form_cat=category)
    q1 = Category.objects.get(users_name=user,app_form_cat=category)
    q1.status = 1
    q1.save()
    return HttpResponse("Accepted successfully!!")

@user_passes_test(lambda u: u.is_superuser)
def RejectForm(request,user,cat_id):
    category = cat[cat_id]
    #q = Category.objects.filter(users_name=user).filter(app_form_cat=category)
    q1 = Category.objects.get(users_name=user,app_form_cat=category)
    q1.status = 2
    q1.save()
    return HttpResponse("Rejected Form!!")


@user_passes_test(lambda u: u.is_superuser)
def view_jury(request):
    context = JurySignup.objects.all()
    return render(request,'BAI_app_v2/view_jury.html',{'context':context})

@login_required
def participant_logout(request):
    logout(request)
    return render(request,'BAI_app_v2/login.html')


def signup(request):
    
    registered = False

    if request.method == 'POST':
        signup_form = SignUpForm(data=request.POST)
        participant_form = ParticipantInfoForm(data=request.POST)

        if signup_form.is_valid() and participant_form.is_valid():
            user = signup_form.save()
            user.set_password(user.password)
            user.save()

            profile = participant_form.save(commit=False)
            profile.user = user
            profile.save()

            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('BAI_app_v2/active_email.html',
                                       {
                                           'user': user,
                                           'domain': current_site.domain,
                                           'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                           'token': default_token_generator.make_token(user),
                                       }
                                       )
            email_subject = 'Builders Association of India Account Verification.'

            to_email = user.email
            email = EmailMessage(
                email_subject,
                message,
                to=[to_email]
            )
            email.send(fail_silently=True)

            registered = True
            UserCategory(users_name=user.username).save()

BAI_app_v2/templates/BAI_app_v2/admin_notverified.html
{% extends "BAI_app_v2/base.html" %}
{% block body_block %}
{% load static %}

<div class="jumbotron mt-5">
    <div class="container mb-5">
      <!-- <p>{{all_entries}}</p> -->
      <p class="h3 mt-5 text-center">List of User(Forms not Verified)</p>

        <div class="row">
          <div class="col-md-3 mt-5">
            <div class="sticky-top">
              <div id="list-example" class="list-group">
                <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:admin_notverified' %}">Not Verified</a>
                <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:admin_verified' %}">Verified</a>
              </div>
            </div>
          </div>
          <div class="col-md-9 mt-5">
              <div class="table-wrapper-scroll-y my-custom-scrollbar">
                <table class="table table-bordered table-striped table-hover text-center" >
                  <thead class="white-text">
                    <tr>
                      <th><strong>Sr No.</strong></th>
                      <th><strong>User</strong></th>
                      <th><strong>Category of Application Form</strong></th>
                      <th><strong>View Form </strong></th>
                      <th><strong>Accept Form</strong></th>
                      <th><strong>Reject Form</strong></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for itr in all_entries %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{itr.0}}</td>
                      <td>{{itr.2}}</td>
                      <td><a href="{% url 'BAI_app_v2:viewForm1_1' itr.0 itr.1 %}"><i class="fas fa-eye fa-lg" style="color: #0288D1;"></i></a></td>
                      <!-- <td><button class="btn btn-link" type="button" data-mdb-toggle="modal" data-mdb-target="#AcceptModal"><i class="fas fa-check fa-lg" style="color: lightgreen;"></i></button></td>
                      
                        <div class="modal fade" id="AcceptModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLongTitle">Confirm Accept Application Form?</h5>
                                  <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                  <img src="../../static/assets/correct.png" alt="tick" style="width:180px;height:180px;">
                                  <h6>Once you Accept Application,and you cannot Reject the form later
                                    <ol>
                                      <li>Applicant will be notified about Acceptance.</li>
                                      <li>You cannot Reject Application after Accepting!</li>
                                      <li>Jury Assigned for this Category will be able to view Application</li>
                                      <li>You can see Accepted Applications in "Verified" tab.</li>
                                    </ol>
                                  </h6>
                                </div>
                                <div class="modal-footer">
                                  <a href="{% url 'BAI_app_v2:AcceptForm' itr.0 itr.1 %}" class="btn btn-primary">Accept Application</a>
                                </div>
                              </div>
                            </div>
                        </div> -->
                      <td><a href="{% url 'BAI_app_v2:AcceptForm' itr.0 itr.1 %}"><i class="fas fa-check fa-lg" style="color: lightgreen;"></i></a></td>
                      <td><a href="{% url 'BAI_app_v2:RejectForm' itr.0 itr.1 %}"><i class="fas fa-times fa-lg" style="color: red;"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
          </div>

        </div>
      </div>
</div>

{% endblock %}

BAI_app_v2/templates/BAI_app_v2/admin_verified.html
{% extends "BAI_app_v2/base.html" %}
{% block body_block %}
{% load static %}

<div class="jumbotron">
    <div class="container mt-5 mb-5">
      <p class="h3 mt-5 text-center">List of User(Forms Verified)</p>
        <div class="row">
          <div class="col-md-3 mt-5">
            <div class="sticky-top">
              <div id="list-example" class="list-group">
                <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:admin_notverified' %}">Not Verified</a>
                <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:admin_verified' %}">Verified</a>
              </div>
            </div>
          </div>
          <div class="col-md-9 mt-5">
              <div class="table-wrapper-scroll-y my-custom-scrollbar">
                <table class="table table-bordered table-striped table-hover text-center" >
                  <thead class="white-text">
                    <tr>
                      <th><strong>Sr No.</strong></th>
                      <th><strong>User</strong></th>
                      <th><strong>Category of Application Form</strong></th>
                      <th><strong>View Form</strong></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for itr in verified %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{itr.0}}</td>
                      <td>{{itr.2}}</td>
                      <td><a href="{% url 'BAI_app_v2:viewForm1_1' itr.0 itr.1 %}"><i class="fas fa-eye fa-lg" style="color: #0288D1;"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>


          </div>

        </div>
      </div>
</div>

{% endblock %}

BAI_app_v2/templates/BAI_app_v2/viewForm2_3.html
{% extends "BAI_app_v2/base.html" %}
{% block body_block %}
{% load static %}

    <div class="container">
      <!-- Horizontal Steppers -->
      <div class="row">
        <div class="col-md-12">

          <!-- Stepers Wrapper -->
          <ul class="stepper stepper-horizontal">

            <li class="completed">
              <a class="nav-link" onclick="href='/BAI_app_v2/form0'">
                <span class="circle">1</span>
                <span class="label">First step</span>
              </a>
            </li>

            <!-- First Step -->
            <li class="incomplete">
              <a href="#step-home">
                <span class="circle">2</span>
                <span class="label">Second step</span>
              </a>
            </li>

            <!-- Second Step -->
            <li class="incomplete">
              <a class="nav-link" onclick="href='/BAI_app_v2/form2'">
                <span class="circle">3</span>
                <span class="label">Third step</span>
              </a>
            </li>

            <!-- Third Step -->
            <li class="incomplete">
              <a class="nav-link" onclick="location.href='/BAI_app_v2/form3.html'">
                <span class="circle">4</span>
                <span class="label">Fourth step</span>
              </a>
            </li>

          </ul>
          <!-- /.Stepers Wrapper -->
          <div class="container">
            <div class="mt-2">
              <div class="row">
                <div class="col-3">
                  <div class="sticky-top">
                    <div id="list-example" class="list-group">
                      <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:viewForm2_1' Others.users_name cat_id %}">Economy</a>
                      <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:viewForm2_2' Others.users_name cat_id %}">Safety/Welfare</a>
                      <a class="list-group-item list-group-item-action" href="{% url 'BAI_app_v2:viewForm2_3' Others.users_name cat_id %}">Others</a>
                    </div>
                  </div>
                </div>
                <div class="col-9">
                  <div class="scrollspy-example z-depth-1">
                    <h4 id="list-item-3">
                      <!--Names of Consultants appointed-->
                    </h4>
                    <!--step 2-3-->
                    <div>
                      <form class="border border-light p-5" action="{% url 'BAI_app_v2:viewForm3' Others.users_name cat_id %}">
                        <p class="h4 mb-4 text-center">Others</p>
                        <p class="text-center">Builder / Contractor(Fill relevant information)</p>
                        <p class="h4 text-center">User: {{Others.users_name}}</p>
                        <p class="h4 mb-2 text-center">Category: {{Others.category_latest}}</p>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>1. What arrangements were made on site for workers
                                accommodation? <br> Provide Photographs. *</b></label><br>
                          </div>
                          <div class="col-3">
                            <p>{{Others.accomodation}}</p>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>2. What sanitary arrangements were made on site for <br>
                                workers? <br> Provide Photographs. *</b></label><br>
                          </div>
                          <div class="col-3">
                            <p>{{Others.sanitary}}</p>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>3. Was Crèche and/or school provided for workers
                                children on site?<br> Provide Photographs.</b></label><br>
                          </div>
                          <div class="col-3">
                            <p>{{Others.school}}</p>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>4. Enlist any pollution control measures adopted <br>
                                during construction to address sound pollution, air <br>
                                pollution, water pollution, waste disposal. <br>
                                Provide Photographs. *</b></label><br>
                          </div>
                          <div class="col-3">
                            <p>{{Others.polution_measures}}</p>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>5. Does your company have any quality accreditation
                                such as ISO?</b></label>
                          </div>
                          <div class="col-3">
                            <p>{{Others.ISO_accreditation}}</p>
                          </div>
                        </div>
                        <hr>
                        <label for="textInput"><b>6. What are the water and energy conservation
                            measures <br> adopted thereby reducing green house
                            gas emissions? *</b></label>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>&emsp;a. During construction</b></label>
                          </div>
                          <div class="col-3">
                            <div class="md-form mt-0">
                              <p>{{Others.conseravation_A}}</p>
                            </div>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>&emsp;b. During occupancy</b></label>
                          </div>
                          <div class="col-3">
                            <div class="md-form mt-0">
                              <p>{{Others.conseravation_B}}</p>
                            </div>
                          </div>
                        </div>
                        <hr>
                        <label for="textInput"><b>7. Specify with proof what are the actions taken to <br>
                            maximize use of renewable energy resources.</b></label>
                        <div class="form-row">
                          <div class="col-9">
                            <div class="md-form mt-0">
                              <p>{{Others.renewable_energy_text}}</p>
                            </div>
                          </div>
                          <div class="col-3">
                            <p>{{Others.renewable_energy_pic}}</p>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>8. Mention measures taken to follow Green Building
                                norms.</b></label>
                          </div>
                          <div class="col-3">
                            <div class="md-form mt-0">
                              <p>{{Others.green_building}}</p>
                            </div>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>9. How effectively you have maintained debris
                                management at site?</b></label>
                          </div>
                          <div class="col-3">
                            <div class="md-form mt-0">
                              <p>{{Others.debris_management}}</p>
                            </div>
                          </div>
                        </div>
                        <hr>
                        <div class="form-row">
                          <div class="col-9">
                            <label for="textInput"><b>10. How many Seminars / Workshops attended by your <br>
                                representative, arranged by BAI or any other
                                organization?</b></label>
                          </div>
                          <div class="col-3">
                            <div class="md-form mt-0">
                              <p>{{Others.seminars}}</p>
                            </div>
                          </div>
                        </div>
                        <hr>
                        
                        <button class="btn btn-info my-4 btn-block" type="submit">Next</button>

                        <p><em>NOTE: Please keep all relevant document ready at site for verification / inspection
                            during the visit of juries.</em> </p>
                      </form>
                    </div>
                    <!--step 2-2-->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.Horizontal Steppers -->
  </div>

{% endblock %}